#+TITLE: \mbox{}
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc date:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

* COMMENT CV options

#+name: setup
#+BEGIN_SRC emacs-lisp :results silent :exports none
  (add-to-list 'org-latex-classes
           '("moderncv"
              "\\documentclass{moderncv}
              [NO-DEFAULT-PACKAGES]
              [EXTRA]"
              ("\\section{%s}" . "\\section*{%s}")
              ("\\subsection{%s}" . "\\subsection*{%s}")
              ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
              ("\\paragraph{%s}" . "\\paragraph*{%s}")
              ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

 (setq org-latex-with-hyperref nil)

 (setq org-latex-default-packages-alist
   '(("AUTO" "inputenc" t)
    ("T1" "fontenc" t)
    ("" "fixltx2e" nil)
    ("" "graphicx" t)
    ("" "longtable" nil)
    ("" "float" nil)
    ("" "wrapfig" nil)
    ("" "rotating" nil)
    ("normalem" "ulem" t)
    ("" "amsmath" t)
    ("" "textcomp" t)
    ("" "marvosym" t)
    ("" "wasysym" nil)
    ("" "amssymb" t)
    ("hidelinks,pdfencoding=auto" "hyperref" nil)
    "\\tolerance=1000"))
#+END_SRC

#+OPTIONS: texht:nil ':t toc:nil H:4
#+LATEX_CLASS: moderncv
#+LATEX_CLASS_OPTIONS: [a4paper,9pt] 
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{enumitem}


% modern CV option 
#+LATEX_HEADER: \moderncvtheme[blue]{classic}
#+LATEX_HEADER: %\moderncvtheme[blue]{casual}
#+LATEX_HEADER: \firstname{Takaaki}
#+LATEX_HEADER: \lastname{FUKAI}
#+LATEX_HEADER: \email{takaaki.fukai@riken.jp}
#+LATEX_HEADER: \address{7-1-26 Minatojima-minami-machi, Chuo-ku,\\Kobe, Hyogo 650-0047, Japan\\}
#+LATEX_HEADER: \phone{+81-78-940-5555}



% Layout option
#+LATEX_HEADER: \setlength{\topmargin}{-18truemm}
#+LATEX_HEADER: \setlength{\oddsidemargin}{-6truemm}
#+LATEX_HEADER: \setlength{\evensidemargin}{-6truemm}
#+LATEX_HEADER: \setlength{\textwidth}{160truemm}
#+LATEX_HEADER: \setlength{\textheight}{241truemm}
#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.0}

* Summary
I received my Ph.D. from the department of computer science, University of Tsukuba in 2018, after obtaining a B.Eng. from Okayama University in 2013.
Since January 2020, I have been postdoctoral research at RIKEN Center of Computational Science.
Before that, I worked for IBM Japan as a software developer.
My research interest centers on how to improve serviceability and security of computer systems without OS-modification and virtualization overhead, by exploiting thin-hypervisor.
One of my important works is that I proposed a live migration scheme that works without OS modification and device virtualization.

* Affiliation
  - Postdoctral researcher in High Performance Big Data Research Team, \newline
    RIKEN Center of Computational Science (R-CCS)
  - Visited Researcher at Information Technology Center, The University of Tokyo

* Research and Work Experience
  - January 2020-Current: *Postdoctral researcher* \newline 
    /High Performance Big Data Research Team RIKEN Center of Computational Science/  \newline
    I am engaged in research about high-performance computing with next-generation hardware.

  - June 2019-Current: *Visited Researcher* \newline
    /Information Technology Center, The University of Tokyo/  \newline
    I am engaged in research about VMM live refreshing with on-demand nested virtualization [[vmm_refreshing]].

  - April 2018-December 2019: *Software Developer*  \newline
    /IBM Japan/  \newline
    I was engaged in the development of a web application, a SaaS cloud service, and a private cloud production.

* Education
  - September 2018: *Doctor of Philosophy in Engineering, University of Tsukuba* \newline
    Supervisor: Professor Kazuhiko Kato \newline

  - March 2015: *Master of Engineering, University of Tsukuba* \newline
    Supervisor: Professor Kazuhiko Kato \newline

  - March 2013: *Bachelor of Engineering, Okayama University* \newline
    Supervisor: Professor Hideo Taniguchi \newline


* Award
  - *IEEE Computer Society Japan Chapter Young Author Award 2019*.\newline
    IEEE Computer Society Tokyo/Japan Joint Chapter, December 2019.\newline

  - *Best Paper Award*.\newline
    The 10th IEEE International Conference on Cloud Computing Technology and Science, December 2018.\newline

  - *Best Paper Award*.\newline
    The 8th IEEE/ACM International Conference on Utility and Cloud Computing, December 2015.\newline
    
    
* Publications
** Journal Paper
#+ATTR_LATEX: :options [label=\textrm{[}\arabic*\textrm{]}, ref=\textrm{[}\arabic*\textrm{]}]
   1. _Takaaki Fukai_, Takahiro Shinagawa, Kazuhiko Kato.\newline
      *Live Migration in Bare-metal Clouds.*\newline
      IEEE Transactions on Cloud Computing, Jul 2018.\newline
      (Open Access: https://ieeexplore.ieee.org/document/8401692)\newline
      <<migration1>>

** International Conference/Workshop Papers (Refereed)
   #+ATTR_LATEX: :options [resume*]
   1. _Takaaki Fukai_, Satoru Takekoshi, Kohei Azuma, Takahiro Shinagawa and Kazuhiko Kato.\newline
      *BMCArmor: A Hardware Protection Scheme for Bare-Metal Clouds.* \newline
      In Proceedings of the 9th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2017), Dec 2017.\newline
      <<protection>>

   2. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, and Kazuhiko Kato.\newline
      *OS-Independent Live Migration Scheme for Bare-metal Clouds.*\newline
      In Proceedings of the 8th IEEE/ACM International Conference on Utility and Cloud Computing (UCC 2015), Dec 2015.\newline
      *[Best paper award]*.\newline
      <<migration2>>

** International Conference/Workshop Posters (Refereed)
   #+ATTR_LATEX: :options [resume*]
   1. Ryosuke Yasuoka, _Takaaki Fukai_ and Takahiro Shinagawa.\newline
      *Toward On-demand Nested Virtualization for Live-Refreshing Cloud Systems*.\newline
      The Fifteenth EuroSys Conference 2020 (EuroSys '20), poster, April, 2020 (To be appear).\newline
      <<vmm_refreshing>>

   2. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, and Kazuhiko Kato.\newline
     *Live Migration of Bare-metal Instances*.\newline
     5th Asia-Pacific Workshop on Systems (APSys 2014), June, 2014\newline
      <<migration3>>

* Other publications
   #+ATTR_LATEX: :options [resume*]
   1. Masanori Misono, Masahiro Ogino, _Takaaki Fukai_, Takahiro Shinagawa.\newline
      *FaultVisor2: Testing Hypervisor Device Drivers against Real Hardware Failures.*\newline
      In Proceedings of the 10th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2018), Dec 2018.\newline
      (Acceptance Ratio: 19.8%) *[Best paper award]*.\newline
      <<faultvisor>>

   2. Iori Yoneji, _Takaaki Fukai_, Takahiro Shinagawa and Kazuhiko Kato.\newline
      *Unified Hardware Abstraction Layer with Device Masquerade.*\newline
      In Proceedings of the 33rd ACM Symposium On Applied Computing (ACM SAC 2018), Apr 2018.\newline

   3. Ilias Avramidis, Michael Mackay, Posco Tso, _Takaaki Fukai_, Takahiro Shinagawa.\newline
      *Live Migration on ARM-based Micro-datacentres.*\newline
      In Proceedings of the 3rd Workshop on Edge Computing (EdgeCom 2018), Jan 2018.\newline


* Skills
  - *Research Expertise* \newline
    Thin-hypervisor, Virtualization, Operating systems, Firmware security, IaaS Clouds

  - *Technical Expertise* \newline
    Intel VT-x, PC-architecture low-level programming, Device driver, Linux kernel, QEMU/KVM

  - *Software service development skills (Technical experience as software developer)* \newline
    Docker, Kubernetes, CI/CD, Microservice architecture, Software test

  - *Software Programming Skills* \newline
    C language(10+ years), x86 assembly, Shell script, Python, Java (Include Android application), TypeScript

  - *Platforms* \newline
    Linux, Mac, Windows

  - *Languages* \newline
    Japanese(Native), English(Intermediate)

* Research Activities
  - April 2020-Current :: Editorial Board Member of IPSJ Transactions on Advanced Computing Systems (ACS)
  - April 2020-Current :: Steering Committee Member of IPSJ Special Interest Group on System Software and Operating Systems (SIGOS)

* Other Information
  - Profile page :: https://fukai-t.github.io/profile-page/
  - ResearchGate :: https://www.researchgate.net/profile/Takaaki_Fukai
  - Linkedin :: https://www.linkedin.com/in/takaaki-fukai-b378a7141/
