#+TITLE:     Takaaki FUKAI (深井貴明)
#+AUTHOR:    Takaaki FUKAI
#+EMAIL:     fukai (at) aist.go.jp
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:nil toc:t \n:n @:t ::t |:t ^:t -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

Japanese version is [[./profile_jp.html][here]]
* Affiliation
  - Researcher in [[https://www.digiarc.aist.go.jp/en/team/ccirt/][Digital Architecture Research Center, National Institute of Advanced Industrial Science and Technology (AIST)]]

* Contact
  - E-mail ::
    takaaki.fukai (at) aist.go.jp
  - Address ::
    2-3-26 Aomi, Koto-ku, Tokyo 135-0064, Japan

* Research Interests
  - OS Kernel, Virtualization Software
    - [[https://www.bitvisor.org/][BitVisor]]
    - [[https://github.com/RIKEN-RCCS/MilvusVisor][MilvusVisor]]
    - Linux
  - Cloud Computing
    - IaaS Cloud
      - Bare-metal Cloud
    - Physical Machine Management
      - Live Migration
      - Hardware Protection

* Degrees
  - September 2018, Doctor of Philosophy in Engineering, University of Tsukuba
  - March 2015, Master of Engineering, University of Tsukuba
  - March 2013, Bachelor of Engineering, Okayama University
* Publications
** Journal Paper
   1. _Takaaki Fukai_, Takahiro Shinagawa, Kazuhiko Kato.
      *Live Migration in Bare-metal Clouds.*
      IEEE Transactions on Cloud Computing,
      Jul 2018.
      (Open Access: https://ieeexplore.ieee.org/document/8401692)

** International Conference Papers (Refereed)
   1. _Takaaki Fukai_, Kento Sato and Takahiro Hirofuchi.
      *Analyzing I/O Performance of a Hierarchical HPC Storage System for Distributed Deep Learning*
      In Proceedings of the 23rd International Conference on Parallel and Distributed Computing, Applications and Technologies (PDCAT’22)
      Dec 2022 (To be appear).
   2. Tabuchi, Akihiro and Shirahata, Koichi and Yamazaki, Masafumi and Kasagi, Akihiko and Honda, Takumi and Kurihara, Kouji and Kawakami, Kentaro and Tabaru, Tsuguchika and Fukumoto, Naoto and Kuroda, Akiyoshi and _Fukai, Takaaki_ and Sato, Kento
      *The 16,384-node Parallelism of 3D-CNN Training on An Arm CPU based Supercomputer*
      2021 IEEE 28th International Conference on High Performance Computing, Data, and Analytics (HiPC)
      Dec. 2021.
   3. Masanori Misono, Masahiro Ogino, _Takaaki Fukai_, Takahiro Shinagawa.
      *FaultVisor2: Testing Hypervisor Device Drivers against Real Hardware Failures.*
      In Proceedings of the 10th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2018),
      Dec 2018. (Acceptance Ratio: 19.8%) *[Best paper award]*.
   4. Iori Yoneji, _Takaaki Fukai_, Takahiro Shinagawa and Kazuhiko Kato.
      *Unified Hardware Abstraction Layer with Device Masquerade.*
      In Proceedings of the 33rd ACM Symposium On Applied Computing (ACM SAC 2018),
      Apr 2018.
   5. Ilias Avramidis, Michael Mackay, Posco Tso, _Takaaki Fukai_, Takahiro Shinagawa.
      *Live Migration on ARM-based Micro-datacentres.*
      In Proceedings of the 3rd Workshop on Edge Computing (EdgeCom 2018),
      Jan 2018.
   6. _Takaaki Fukai_, Satoru Takekoshi, Kohei Azuma, Takahiro Shinagawa and Kazuhiko Kato.
      *BMCArmor: A Hardware Protection Scheme for Bare-Metal Clouds.*
      In Proceedings of the 9th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2017),
      Dec 2017.
   7. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, Kazuhiko Kato.
      *OS-Independent Live Migration Scheme for Bare-metal Clouds.*
      In Proceedings of the 8th IEEE/ACM International Conference on Utility and Cloud Computing,
      December 2015.
      *[Best paper award]*.

** International Conference Papers (Refereed)
   1. Farrell, Steven and Emani, Murali and Balma, Jacob and Drescher, Lukas and Drozd, Aleksandr and Fink, Andreas and Fox, Geoffrey and Kanter, David and Kurth, Thorsten and Mattson, Peter and Mu, Dawei and Ruhela, Amit and Sato, Kento and Shirahata, Koichi and Tabaru, Tsuguchika and Tsaris, Aristeidis and Balewski, Jan and Cumming, Ben and Danjo, Takumi and Domke, Jens and _Fukai, Takaaki_ and Fukumoto, Naoto and Fukushi, Tatsuya and Gerofi, Balazs and Honda, Takumi and Imamura, Toshiyuki and Kasagi, Akihiko and Kawakami, Kentaro and Kudo, Shuhei and Kuroda, Akiyoshi and Martinasso, Maxime and Matsuoka, Satoshi and Mendon\ccedil{}a, Henrique and Minami, Kazuki and Ram, Prabhat and Sawada, Takashi and Shankar, Mallikarjun and John, Tom St. and Tabuchi, Akihiro and Vishwanath, Venkatram and Wahib, Mohamed and Yamazaki, Masafumi and Yin, Junqi.
      *MLPerf\trade{} HPC: A Holistic Benchmark Suite for Scientific Machine Learning on HPC Systems.*
      2021 IEEE/ACM Workshop on Machine Learning in High Performance Computing Environments (MLHPC).
      November 2021.

** Domestic Workshop Papers (Non-Refereed)
   (Sorry for information in Japanese, but there is no official information in English)

  1. 森 真誠(†), _深井 貴明_, 山本 啓二, 広渕 崇宏, 朝香 卓也．
     *Root権限使用可能なArmスパコン実現に向けた軽量ハイパバイザの設計と実装．*
     第157回 システムソフトウェアとオペレーティング・システム研究会．
     2022年9月．
     †: *Best presentation award*
  2. 長塚 向紀, _深井 貴明_, 山本 啓二, 宮島 敬明, 広渕 崇宏． 
     *Armプロセッサにおける軽量ハイパバイザの性能評価．*
     第157回 システムソフトウェアとオペレーティング・システム研究会．
     2022年9月．
  3. _深井 貴明_, 広渕 崇宏, 高野 了成, Akram Ben Ahmed, 佐藤 賢斗．
     *FPGAによる次世代メモリのエミュレーション機構．*
     第180回 ハイパフォーマンスコンピューティング研究発表会 (SWoPP2021)
     2021年7月．
  4. 荻野 将拓, 味曽野 雅史, _深井 貴明_, 品川 高廣．
     *ハードウェア障害に対するハイパーバイザの対故障性検証．*
     第143回 システムソフトウェアとオペレーティング・システム研究会．
     2018年5月
  5. 東 耕平, 竹腰 開, _深井 貴明_, 品川 高廣, 加藤 和彦
     *ベアメタルクラウドにおけるハードウェア保護*
     第136回 システムソフトウェアとオペレーティング・システム研究会．
     2016年2月
  6. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案*
     第127回 システムソフトウェアとオペレーティング・システム研究会．
     2013年12月
   [[./files/OS127-fukai.pdf][PDF]] [[./ipsjnotice.html][ここに掲載した著作物の利用に関する注意]]
** International Conference/Workshop Posters (Refereed)
   1. _Takaaki Fukai_ and Kento Sato.
      *Measurement of I/O Performance on a Hierarchical File System for Distributed Deep Neural Network.*
      The 4th R-CCS International symposium
      February, 2022.

   2. _Takaaki Fukai_ and Kento Sato.
      *Performance Measurement of a Hierarchical File System for Distributed Deep Neural Network Training.*
      The International Conference on High Performance Computing in Asia-Pacific Region (HPC Asia 2022)
      January, 2022.

   3. _Takaaki Fukai_ and Kento Sato.
      *Measurement of I/O performance for distributed deep neural networks on Fugaku*.
      The 3rd R-CCS International Symposium 2021.
      February, 2021.

   4. Ryosuke Yasuoka, _Takaaki Fukai_ and Takahiro Shinagawa.
      *Toward On-demand Nested Virtualization for Live-Refreshing Cloud Systems*.
      The Fifteenth EuroSys Conference 2020 (EuroSys ’20).
      April, 2020 (To be appear).

   5. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, and Kazuhiko Kato.
     *Live Migration of Bare-metal Instances*
     5th Asia-Pacific Workshop on Systems (APSys 2014).
     June, 2014

** Domestic Workshop Posters (Non-Refereed)
   (Sorry for information in Japanese, but there is no official information in English)

  1. 葛野弘樹， _深井貴明_.
    *仮想化ソフトウェアのセキュア化に向けた脆弱性の調査分析.*
    第34回コンピュータシステム・シンポジウム (ComSys 2022).
    2022年12月.
  2. 安岡 亮輔， _深井 貴明_ ，品川 高廣， 加藤 和彦.
    *ネステッド仮想化の動的 ON/OFF による仮想マシンモニタ若化.*
    第28回コンピュータシステム・シンポジウム (ComSys2016).
    2016年11月.
  3. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案.*
     第11回 ディペンダブルシステムワークショップ (DSW 2013).
     2013年12月.
  4. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案*
     第25回コンピュータシステム・シンポジウム (ComSys2013).
     2013年12月.

** Other presentations (Domestic)
   (Sorry for information in Japanese, but there is no official information in English)

   1.  _深井 貴明_
      トップカンファレンス・ジャーナル採択論文講演
      (採択論文情報: Takaaki Fukai, Takahiro Shinagawa, Kazuhiko Kato, "Live Migration in Bare-metal Clouds", IEEE Transactions on Cloud Computing, July 2018.)
      第31回コンピュータシステム・シンポジウム (ComSys2019）

* Awards
  - *IEEE Computer Society Japan Chapter Young Author Award 2019*
    IEEE Computer Society Tokyo/Japan Joint Chapter, December 2019

  - *Best Paper Award*
    The 10th IEEE International Conference on Cloud Computing Technology and Science, December 2018

  - *Best Paper Award*
    The 8th IEEE/ACM International Conference on Utility and Cloud Computing, December 2015

  - *岡山大学工学部優秀学生賞*
    Faculty of Engineering, Okayama University, March 2013

* Grants
** Principal Investigator
- 「共用 HPC における管理者権限の利用を許す計算資源提供」 Grant-in-Aid for Early-Career Scientists, Japan Society for the Promotion of Science(JSPS), April 2021--March 2024.

* Research activities
** Editorial Board Member
- April 2020--Present: IPSJ Transactions on Advanced Computing Systems
** Steering Committee Member
- April 2020--Present: IPSJ Special Interest Group on System Software and Operating Systems (SIGOS)
** Others
- The 3rd R-CCS International Symposium 2021. Online arrangement chair.

* Work Experience
- April 2022--Present: Researcher in Digital Architecture Research Center, National Institute of Advanced Industrial Science and Technology (AIST)
- January 2020--March 2022: Postdoctoral Researcher in RIKEN Center of Computational Science (R-CCS)
- April 2018-December 2019: Software Developer at IBM Japan
  - Worked as QA engineer of a web application and DevOps engineer of a cloud productions
  - Technical experience: Software test, CI/CD, Jenkins, Docker, Kubernetes, Helm


* Other Activity
  - ResearchGate :: https://www.researchgate.net/profile/Takaaki_Fukai
  - Linkedin :: https://www.linkedin.com/in/takaaki-fukai-b378a7141/?originalSubdomain=jp
  - Slideshare :: https://www.slideshare.net/DeepTokikane/presentations
  - Github :: https://github.com/fukai-t
  - Bitbucket :: https://bitbucket.org/ftakaaki/
* Update History
  - 2022/12/29 Update /Affiliation/, /Contact/, /Publications/, and /Work Experience/
  - 2021/09/10 Add /Grants/ and /Research activities/, Update /Work Experience/ and /Publications/
  - 2020/04/07 Update /Publications/
  - 2020/03/10 Add /Work Experience/ and update /Affiliation/, /Contact/, /Publications/, and /Award/
  - 2019/08/12 Update Affiliation, Contact, Degree, Publications, Award, and Other Activity sections
  - 2019/08/11 Move from http://www.osss.cs.tsukuba.ac.jp/~fukai to https://fukai-t.github.io/profile-page/
  - 2018/02/14 Update Affiliation, Research Interests, and Publications
  - 2016/03/14 Update Publications & Add other activity
  - 2015/12/11 Add English version page & Update Research Interests, Publications & Add Award
  - 2015/05/09 Add Affiliation, Degrees, and Publications
  - 2014/03/12 Open this page

