#+TITLE:     Takaaki FUKAI (深井貴明)
#+AUTHOR:    Takaaki FUKAI
#+EMAIL:     fukai@osss.cs.tsukuba.ac.jp
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:nil toc:t \n:n @:t ::t |:t ^:t -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />

Japanese version is [[./profile_jp.html][here]]
* Affiliation
  - Postdoctoral Researcher at RIKEN
  - Visited Researcher at Information Technology Center, The University of Tokyo

* Contact
  - E-mail ::
	      takaaki.fukai (at) riken.jp
  - Address ::
	       RIKEN Center for Computational Science (RIKEN R-CCS)
	       7-1-26 Minatojima-minami-machi, Chuo-ku, Kobe, Hyogo 650-0047, Japan

* Research Interests
  - OS Kernel, Virtualization Software
    - BitVisor
    - Linux
  - Cloud Computing
    - IaaS Cloud
      - Bare-metal Cloud
    - Physical Machine Management
      - Live Migration
      - Hardware Protection

* Degrees
  - September 2018, Doctor of Philosophy in Engineering, University of Tsukuba
  - March 2015, Master of Engineering, University of Tsukuba
  - March 2013, Bachelor of Engineering, Okayama University
* Publications
** Journal Paper
   1. _Takaaki Fukai_, Takahiro Shinagawa, Kazuhiko Kato.
      *Live Migration in Bare-metal Clouds.*
      IEEE Transactions on Cloud Computing,
      Jul 2018.
      (Open Access: https://ieeexplore.ieee.org/document/8401692)

** International Conference Papers (Refereed)
   1. Masanori Misono, Masahiro Ogino, _Takaaki Fukai_, Takahiro Shinagawa.
      *FaultVisor2: Testing Hypervisor Device Drivers against Real Hardware Failures.*
      In Proceedings of the 10th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2018),
      Dec 2018. (Acceptance Ratio: 19.8%) *[Best paper award]*.
   2. Iori Yoneji, _Takaaki Fukai_, Takahiro Shinagawa and Kazuhiko Kato.
      *Unified Hardware Abstraction Layer with Device Masquerade.*
      In Proceedings of the 33rd ACM Symposium On Applied Computing (ACM SAC 2018),
      Apr 2018.
   3. Ilias Avramidis, Michael Mackay, Posco Tso, _Takaaki Fukai_, Takahiro Shinagawa.
      *Live Migration on ARM-based Micro-datacentres.*
      In Proceedings of the 3rd Workshop on Edge Computing (EdgeCom 2018),
      Jan 2018.
   4. _Takaaki Fukai_, Satoru Takekoshi, Kohei Azuma, Takahiro Shinagawa and Kazuhiko Kato.
      *BMCArmor: A Hardware Protection Scheme for Bare-Metal Clouds.*
      In Proceedings of the 9th IEEE International Conference on Cloud Computing Technology and Science (CloudCom 2017),
      Dec 2017.
   5. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, Kazuhiko Kato.
      *OS-Independent Live Migration Scheme for Bare-metal Clouds.*
      In Proceedings of the 8th IEEE/ACM International Conference on Utility and Cloud Computing,
      December 2015.
      *[Best paper award]*.
** Domestic Workshop Papers (Non-Refereed)
   (Sorry for information in Japanese, but there is no official information in English)
  1. 荻野 将拓, 味曽野 雅史, _深井 貴明_, 品川 高廣．
     *ハードウェア障害に対するハイパーバイザの対故障性検証．*
     第143回 システムソフトウェアとオペレーティング・システム研究会．
     2018年5月
  2. 東 耕平, 竹腰 開, _深井 貴明_, 品川 高廣, 加藤 和彦
     *ベアメタルクラウドにおけるハードウェア保護*
     第136回 システムソフトウェアとオペレーティング・システム研究会．
     2016年2月
  3. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案*
     第127回 システムソフトウェアとオペレーティング・システム研究会．
     2013年12月
   [[./files/OS127-fukai.pdf][PDF]] [[./ipsjnotice.html][ここに掲載した著作物の利用に関する注意]]
** International Workshop Posters (Refereed)
   1. _Takaaki Fukai_, Yushi Omote, Takahiro Shinagawa, and Kazuhiko Kato.
     *Live Migration of Bare-metal Instances*
     5th Asia-Pacific Workshop on Systems (APSys 2014).
     June, 2014
** Domestic Workshop Posters (Non-Refereed)
   (Sorry for information in Japanese, but there is no official information in English)
  1. 安岡 亮輔， _深井 貴明_ ，品川 高廣， 加藤 和彦
    *ネステッド仮想化の動的 ON/OFF による仮想マシンモニタ若化*
    第28回コンピュータシステム・シンポジウム．(ComSys2016)
    2016年11月
  2. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案*
     第11回 ディペンダブルシステムワークショップ．(DSW 2013)
     2013年12月
  3. _深井 貴明_ ，表 祐志，品川 高廣，加藤 和彦．
     *物理マシン間のライブマイグレーション手法の提案*
     第25回コンピュータシステム・シンポジウム．(ComSys2013)
     2013年12月
** Other presentations (Domestic)
   (Sorry for information in Japanese, but there is no official information in English)

   1.  _深井 貴明_
      トップカンファレンス・ジャーナル採択論文講演
      (採択論文情報: Takaaki Fukai, Takahiro Shinagawa, Kazuhiko Kato, "Live Migration in Bare-metal Clouds", IEEE Transactions on Cloud Computing, July 2018.)
      第31回コンピュータシステム・シンポジウム (ComSys2019）

* Award
  - *IEEE Computer Society Japan Chapter Young Author Award 2019*
    IEEE Computer Society Tokyo/Japan Joint Chapter, December 2019

  - *Best Paper Award*
    The 10th IEEE International Conference on Cloud Computing Technology and Science, December 2018

  - *Best Paper Award*
    The 8th IEEE/ACM International Conference on Utility and Cloud Computing, December 2015

  - *岡山大学工学部優秀学生賞*
    Faculty of Engineering, Okayama University, March 2013

* Work Experience
  - April 2018 -- December 2019: Software Developer at IBM Japan
    - Worked as QA engineer of a web application and DevOps engineer of a cloud productions
    - Technical experience: Software test, CI/CD, Jenkins, Docker, Kubernetes, Helm


* Other Activity
  - ResearchGate :: https://www.researchgate.net/profile/Takaaki_Fukai
  - Linkedin :: https://www.linkedin.com/in/takaaki-fukai-b378a7141/?originalSubdomain=jp
  - Slideshare :: http://www.slideshare.net/DeepTokikane/presentations
  - Github :: https://github.com/fukai-t
  - Bitbucket :: https://bitbucket.org/ftakaaki/
* Update History
  - 2020/03/10 Add /Work Experience/ and update /Affiliation/, /Contact/, /Publications/, and /Award/
  - 2019/08/12 Update Affiliation, Contact, Degree, Publications, Award, and Other Activity sections
  - 2019/08/11 Move from http://www.osss.cs.tsukuba.ac.jp/~fukai to https://fukai-t.github.io/profile-page/
  - 2018/02/14 Update Affiliation, Research Interests, and Publications
  - 2016/03/14 Update Publications & Add other activity
  - 2015/12/11 Add English version page & Update Research Interests, Publications & Add Award
  - 2015/05/09 Add Affiliation, Degrees, and Publications
  - 2014/03/12 Open this page

